import assert from 'node:assert/strict';
import { Types } from 'mongoose';
Object.assign(process.env, {MONGODB_URI:'mongodb://127.0.0.1/test',JWT_SECRET:'test-secret-only-123456789012345',DISCORD_CLIENT_ID:'test',DISCORD_CLIENT_SECRET:'test',DISCORD_REDIRECT_URI:'http://localhost/callback',BOT_API_TOKEN:'test-only-123456789'});
const { importGameStatSnapshots } = await import('../src/controllers/dashboard.controller.js');
const { MemberModel } = await import('../src/models/member.model.js');
const alliance = {_id: new Types.ObjectId(), tag:'KoG'};
const farm = {_id:new Types.ObjectId(),uid:'24603190',ign:'Non Toxic',discordId:'123456789012345678',power:10000000,powerHistory:[],statHistory:[]};
const main = {_id:new Types.ObjectId(),uid:'24055137',ign:'Toxic',discordId:'topn:24055137',power:45000000,powerHistory:[{date:new Date('2026-08-01'),power:45000000}],statHistory:[]};
const shell = {_id:new Types.ObjectId(),uid:'discord-234567890123456789',ign:'Non Toxic',discordId:'234567890123456789',power:0,powerHistory:[],statHistory:[]};
let records:any[]=[farm,main,shell]; let ops:any[]=[];
(MemberModel as any).find=()=>({select(){return this},limit(){return this},lean:async()=>records});
(MemberModel as any).bulkWrite=async (batch:any[])=>{ops.push(...batch);return {}};
const run=()=>importGameStatSnapshots(alliance,[{rows:[{uid:'24055137',ign:'Toxic',power:45552739,alliance:'KoG',stats:{}},{uid:'24603190',ign:'Non Toxic',power:9968930,alliance:'KoG',stats:{}}],snapshotDate:new Date('2026-08-14'),source:'TopN CSV',filename:'rank.csv'}],'topn');
await run();
assert.equal(ops.some(x=>x.deleteOne),false,'existing main must never be deleted for related Discord shell');
assert.equal(ops.find(x=>x.updateOne.update.$set.uid==='24055137').updateOne.filter._id,main._id);
records=[farm];ops=[];const result=await run();
assert.equal(result.created,1,'missing Toxic main is recreated independently');
assert.equal(ops.find(x=>x.updateOne.update.$set.uid==='24055137').updateOne.update.$setOnInsert.discordId,'topn:24055137');
assert.equal(farm.uid,'24603190');
console.log('Real Toxic UID import regression passed: existing main retained, missing main created, farm preserved.');
