import assert from 'node:assert/strict';
import express from 'express';
import cookieParser from 'cookie-parser';
Object.assign(process.env,{MONGODB_URI:'mongodb://localhost/test',JWT_SECRET:'test-secret-only-123456789012345',DISCORD_CLIENT_ID:'test',DISCORD_CLIENT_SECRET:'test',DISCORD_REDIRECT_URI:'http://localhost/callback',BOT_API_TOKEN:'test-only-123456789'});
const {authRouter}=await import('../src/routes/auth.routes.js');const {errorHandler}=await import('../src/middleware/errorHandler.js');const {UserModel}=await import('../src/models/user.model.js');
(UserModel as any).findOne=()=>{throw Error('Migration OAuth must not create a normal Kella session or user');};
const originalFetch=globalThis.fetch;globalThis.fetch=async(input:any,init:any)=>{if(String(input)==='https://discord.com/api/oauth2/token')return new Response(JSON.stringify({access_token:'test',token_type:'Bearer'}));if(String(input)==='https://discord.com/api/users/@me')return new Response(JSON.stringify({id:'123456789012345678',username:'test'}));return originalFetch(input,init);};
const app=express();app.use(cookieParser());app.use('/auth',authRouter);app.use(errorHandler);const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base='http://127.0.0.1:'+(server.address() as any).port;
try{const start=await fetch(base+'/auth/discord?migration=1',{redirect:'manual'});assert.equal(start.status,302);const state=new URL(start.headers.get('location')!).searchParams.get('state');const cookie=start.headers.get('set-cookie')!.split(';')[0];const callback=await fetch(base+'/auth/discord/callback?code=test&state='+state,{redirect:'manual',headers:{cookie}});assert.equal(callback.status,302);assert.equal(callback.headers.get('location'),'/migration');const cookies=callback.headers.get('set-cookie')||'';assert.ok(cookies.includes('kella_migration_discord='));assert.ok(!cookies.includes('cod_amp_session='));console.log('Migration OAuth verification is scoped to Migration and grants no member/admin session.');}finally{server.close();globalThis.fetch=originalFetch;}
