import assert from 'node:assert/strict';
import { collectSummaryHistory, summaryChunks, SUMMARY_WINDOW_MS, type SummaryMessage } from '../src/services/chatSummary.js';
const now = Date.now();
const msg = (id: number, age = id * 1000): SummaryMessage => ({id: String(10000-id),createdTimestamp: now-age,content: 'plan '+id,author:{bot:false,username:'player'}});
const first = Array.from({length:100},(_,i)=>msg(i));
first[1].author = {bot:true,username:'bot'};
first[2].content = ' ';
const second = [msg(100),msg(101,SUMMARY_WINDOW_MS),msg(102,SUMMARY_WINDOW_MS+1)];
let calls=0;
const result = await collectSummaryHistory(async before => { calls++; if(calls===1){assert.equal(before,undefined);return first;} assert.equal(before,first[99].id);return second; },now);
assert.equal(calls,2);
assert.equal(result.length,100);
assert.equal(result[0].id,second[1].id);
assert.ok(result.every(m=>!m.author.bot && m.content.trim() && m.createdTimestamp>=now-SUMMARY_WINDOW_MS));
assert.deepEqual(await collectSummaryHistory(async()=>[],now),[]);
assert.deepEqual(await collectSummaryHistory(async()=>[msg(1,-1000)],now),[]);
const chunks=summaryChunks(result,500);
assert.ok(chunks.every(c=>c.length<=500));
assert.ok(chunks.join('').includes('plan 101'));
assert.ok(chunks.join('').includes('plan 0'));
await assert.rejects(collectSummaryHistory(async()=>[],now,Date.now()-1),/too busy/);
console.log('Five-hour boundary, pagination, bot/empty/future filtering and complete chunking passed.');
import { summarizeWithGroq } from '../src/services/groqSummary.js';
let requests=0;
const mock = async (_url: unknown, init: any) => {
  requests++;
  const body=JSON.parse(init.body);
  assert.ok(body.messages[0].content.includes('untrusted data'));
  return new Response(JSON.stringify({choices:[{message:{content:'• Rally at 18:00. @everyone'}}]}),{status:200});
};
assert.ok((await summarizeWithGroq(['a','b'],'test-key',mock as typeof fetch)).includes('[mention]'));
assert.equal(requests,3);
await assert.rejects(summarizeWithGroq(['a'],'test',async()=>new Response('',{status:429})),/free summary quota/);
await assert.rejects(summarizeWithGroq(['a'],'test',async()=>new Response('{}',{status:200})),/no summary/);
assert.match(await summarizeWithGroq([],'test',async()=>{throw new Error('Must not call AI for empty history');}),/No text conversation/);
console.log('Summary merge, prompt boundaries, mention suppression, quota and empty-history handling passed.');
