import { Router } from "express";
import { analyticsRouter } from "./analytics.routes.js";
import { announcementRouter } from "./announcement.routes.js";
import { attendanceRouter } from "./attendance.routes.js";
import { authRouter } from "./auth.routes.js";
import { botRouter } from "./bot.routes.js";
import { diplomacyRouter } from "./diplomacy.routes.js";
import { eventRouter } from "./event.routes.js";
import { memberRouter } from "./member.routes.js";
import { operationRouter } from "./operation.routes.js";
import { recruitmentRouter } from "./recruitment.routes.js";
import { rootsOfWarRouter } from "./rootsOfWar.routes.js";
import { settingsRouter } from "./settings.routes.js";
import { shieldRouter } from "./shield.routes.js";
import { taskRouter } from "./task.routes.js";

export const apiRouter = Router();

apiRouter.get("/health", (_req, res) => res.json({ ok: true, service: "cod-amp-api" }));
apiRouter.use("/auth", authRouter);
apiRouter.use("/members", memberRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/operations", operationRouter);
apiRouter.use("/shields", shieldRouter);
apiRouter.use("/recruitment", recruitmentRouter);
apiRouter.use("/tasks", taskRouter);
apiRouter.use("/events", eventRouter);
apiRouter.use("/roots-of-war", rootsOfWarRouter);
apiRouter.use("/diplomacy", diplomacyRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/announcements", announcementRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/bot", botRouter);
